### ISSUE TITLE
weight_C.tar.gz missing

### ISSUE THREAD

**Issue by surrealbridge** [uedaLabR/nanoDoc2#2]
Hi, 

When I go to this link https://zenodo.org/record/6587256 from 
wget https://zenodo.org/record/6587256/files/weight_C.tar.gz
weight_T.tar.gz is there. I went to the link for all 4 nucleotides and it seems T is repeated twice but there is no C. Is the file in the 6587256 actually C or is T uploaded twice?

Thanks

**Comment by uedaLabR** [comment]
I am sorry that I mistakenly upload the T twice.
Now I uploaded C to the link below.
https://zenodo.org/api/files/99a98533-04bd-42b0-ad8e-9d0ebe5c91aa/weight_C.tar.gz

Thanks

**Comment by surrealbridge** [comment]
Thank you!
